apiVersion: v1
kind: Pod
metadata:
  name: two
  labels:
    app: two
spec:
  containers:
  - name: two
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: two-service
spec:
  selector:
    app: two
  ports:
  - port: 80
    targetPort: 80

