apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    name: sidecar
spec:
  containers:
  - name: sidecar
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - name: cache-vol
        mountPath: /cache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes: 
      - name: cache-vol
        emptyDir: {}
