apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
stringData:
  db: mongodb://user:password@localhost:27017
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    env:
      - name: DB
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
